version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: clients-db
    environment:
      POSTGRES_DB: clientsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  angular-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data: