CREATE TABLE IF NOT EXISTS client (
    id VARCHAR(255) PRIMARY KEY,
    shared_key VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);